server:
  port: 8082

spring:
  application:
    name: ems-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Siddhartha12345/ems-common-config
          clone-on-start: true